language: node_js
node_js:
- '10'
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
script:
- npm run lint{{if hasTest}}
- npm test
after_success:
- npm run coverage{{/if}}
git:
  depth: 1
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: npm
  skip_cleanup: true
  email: {{email}}
  api_key:
    secure: todo
  on:
    tags: true
    repo: {{author}}/{{project}}
    branch: master
